import Config

ecto_log_level =
  case System.get_env("ECTO_LOG_LEVEL", "warning") do
    "false" -> false
    value -> String.to_atom(value)
  end

db_pool_size =
  System.get_env("DB_POOL_SIZE", "5")
  |> String.to_integer()

# Configure your database
config :stream_genome, StreamGenome.Repo,
  username: "postgres",
  password: "postgres",
  hostname: System.get_env("POSTGRES_HOST", "localhost"),
  database: "stream_genome_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  log: ecto_log_level,
  pool_size: db_pool_size

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :stream_genome, StreamGenomeWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [
    ip:
      case System.get_env("PHX_BIND", "127.0.0.1") do
        "0.0.0.0" -> {0, 0, 0, 0}
        _loopback -> {127, 0, 0, 1}
      end
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "ephutSUlRDsoKO3CfSKYmv70FeLr8MGnhCv8VdYhzi/iq44n5b0nQWwfB+AKjBlA",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:stream_genome, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:stream_genome, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :stream_genome, StreamGenomeWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/stream_genome_web/router\.ex$",
      ~r"lib/stream_genome_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :stream_genome, dev_routes: true

config :stream_genome, open_admin?: true

youtube_discovery_adapter =
  case System.get_env("YOUTUBE_DISCOVERY_ADAPTER", "yt_dlp") do
    "atom_feed" -> :atom_feed
    _yt_dlp -> :yt_dlp
  end

config :stream_genome, :youtube_crawler,
  discovery_adapter: youtube_discovery_adapter,
  archive_limit: String.to_integer(System.get_env("YOUTUBE_ARCHIVE_LIMIT", "7500")),
  transcript_languages: System.get_env("YOUTUBE_TRANSCRIPT_LANGS", "ru-orig,ru"),
  yt_dlp_js_runtime: System.get_env("YT_DLP_JS_RUNTIME", "node"),
  yt_dlp_cookies_path: System.get_env("YT_DLP_COOKIES_PATH", "/data/youtube/cookies.txt"),
  yt_dlp_path: System.get_env("YT_DLP_PATH", "yt-dlp"),
  proxy: [
    scheme: :http,
    host: System.get_env("YOUTUBE_PROXY_HOST", "127.0.0.1"),
    port: String.to_integer(System.get_env("YOUTUBE_PROXY_PORT", "10808"))
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
